version: '3.0'
services:
  postgres:
    image: postgres:15.1-alpine
    volumes:
      #- ./postgres/mattermost.sql:/docker-entrypoint-initdb.d/00-mattermost.sql
      - ./backup/mattermost.sql:/docker-entrypoint-initdb.d/00-mattermost.sql
      - ./postgres/setup-synapse.sql:/docker-entrypoint-initdb.d/01-setup-synapse.sql
      # - ./postgres/synapse.sql:/docker-entrypoint-initdb.d/02-synapse.sql
      - ./backup/synapse.sql:/docker-entrypoint-initdb.d/02-synapse.sql
      - ./postgres/setup-bridge.sql:/docker-entrypoint-initdb.d/03-setup-bridge.sql
      - ./docker-scripts/dump_db.sh:/dump_db.sh

    environment:
      #We create synapse database in 01-setup.sql
      - POSTGRES_USER=mattermost
      - POSTGRES_DB=mattermost
      - POSTGRES_PASSWORD=hunter2
    ports:
      - '5432:5432'
    networks:
      - my_net

  mattermost:
    build: mattermost
    ports:
      - '8065:8065'
    networks:
      - my_net
    depends_on:
      - postgres

  synapse:
    build: synapse
    ports:
      - '8008:8008'
    volumes:
      - ./synapse/registration.yaml:/etc/synapse/registration.yaml
      - ./synapse/homeserver.yaml:/etc/synapse/homeserver.yaml

    networks:
      - my_net
    depends_on:
      - postgres

  appservice:
    build: appservice
    ports:
      - '8022:22'
    networks:
      - my_net

  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    volumes:
      - ./element/element-config.json:/app/config.json
    ports:
      - '8080:80'
    networks:
      - my_net
    depends_on:
      - synapse

networks:
  my_net:
    driver: bridge
